[package]
name = "static-server"
version = "0.1.0"
authors = ["cuiyunjing < 15921219561 >"]
edition = "2018"

[dependencies]
actix-web        = "3.3.2"
actix-files       = "0.5.0"
dotenv           = "0.15.0"
nix = "0.19.1"
